### ISSUE TITLE
Landing page does not load when I click on the URL in the readme

### ISSUE THREAD

**Issue by mikeysan** [Sammeeey/CoderMatching#68]
*Summary*
I was attempting to test the app by clicking on the link in the README page (https://codermatching.herokuapp.com/).

*System:*
Windows 10
Google Chrome Browser (latest as of time of writing)

*Expected result:*
Landing page

*Actual result:*
Application Error
![image](https://user-images.githubusercontent.com/13338176/213905170-bfbe0435-1edc-462e-828f-4aa8954fe2b7.png)

*Other*
Should I only attempt to access the link via mobile phone?

**Comment by Sammeeey** [comment]
Thank you.
The app doesn't work anymore because Heroku free tire is down.
